### ISSUE TITLE
Envoi SMS : à un groupe indépendamment du CG

### ISSUE THREAD

**Issue by aanli** [EsupPortail/esup-smsu#20]
Avoir la possibilité de sélectionner un type de destinataire "Groupe d'utilisateurs indifférenciés" où on n'applique pas la condition d'adhésion au service pour lui envoyer un SMS.

Le SMS sera envoyé à tous les utilisateurs présents dans le groupe sélectionné en bypassant la condition d'adhésion au service SMSU.

Cas d'usage très spécifique (alerte incendie, attentat, ...) et pouvoir déléguer l'envoi de SMS à des fonctionnels (responsable sécurité, ...) sans passer par des filtres LDAP (complexe pour des utilisateurs standard).

**Comment by JGallot** [comment]
Bonjour,

Nous apprécierions que cette fonctionnalité soit aussi développée

Cdlt,

**Comment by prigaux** [comment]
Après avoir regardé le code, le plus adapté serait de :
- créer une fonction FCTN_SMS_ENVOI_SERVICE_IGNORE_CG avec comme libellé "Envoi SMS en incluant les non adhérents"
- autoriser le choix du thème/partenaire "Inclure les non adhérents"
- peut-être renommer "thème/partenaire" ?
- prendre en compte le serviceKey "FCTN_SMS_ENVOI_SERVICE_IGNORE_CG" dans ldapUtils.getConditionFriendlyLdapUsersFromUid

**Comment by prigaux** [comment]
Disponible en test sur la branche "wip".
Passé en production à l'université Paris 1. Si tout fonctionne correctement, je mettrai sur la branche "master".

**Comment by JGallot** [comment]
Bonjour, 

Merci Pascal. Je regarderai ce point sous 15 jours max.
