### ISSUE TITLE
Fonction d'auto-approbation

### ISSUE THREAD

**Issue by aanli** [EsupPortail/esup-smsu#21]
Ajouter une fonction d'auto-approbation des envois aux groupes.
L'utilisateur qui aura ce rôle pourra envoyer des SMS à n'importe quel groupe et valider ces envois.

L'objectif est de donner la possibilité à des utilisateurs de valider leur propre envoi de SMS à des groupes (ou ensemble de numéros) sans qu'ils soient pour autant défini, au préalable, comme superviseur de ce groupe.

**Comment by prigaux** [comment]
Pourquoi ne pas mettre un quota "Nb. max de destinataires/envoi" élevé pour ce "groupe d'envoi" ?

NB : depuis la version 3.0 (cf https://github.com/EsupPortail/esup-smsu/pull/19), l'interface affiche "Cette sélection correspondrait à 290 numéros." lors de l'envoi à un groupe. Donc l'utilisateur est au courante du nombre potentiel de SMS qui sera envoyé.

**Comment by aanli** [comment]
"nb max" concerne les envois à des listes de num ou d'users. Pas à des groupes. l'approbation est systematique pour les envois à des groupes.

**Comment by aanli** [comment]
la solution "nb max" conviendrait pour les envois à des listes. Meme s il est préférable d'y mentionner une quantité raisonnable pour éviter des erreurs d'envoi à des centaines d'users sans confirmation.

**Comment by prigaux** [comment]
Plutôt que l'auto-approbation, on va plutôt donner la possibilité d'avoir les membres d'un groupe comme superviseurs. Cela permettra d'avoir un "groupe d'envoi" dont les superviseurs seraient les membres du groupe => donc auto-approbation. Mais cela permettra aussi d'autres choses comme mettre comme superviseurs d'un groupe G le groupe des responsables du groupe G.

**Comment by aanli** [comment]
Super! Cela veut dire que la fonctionnalité existe déjà ;-)!!

Il suffirait donc que je crée un groupe d'envoi et mettre comme superviseur(s) de ce groupe le(s) utilisateur(s) qui peu(ven)t auto-approuver les envois.
