### ISSUE TITLE
Correction orthographique écran de validation code SMS

### ISSUE THREAD

**Issue by JGallot** [EsupPortail/esup-smsu#23]
Lorsqu'un utilisateur souscrit au service avec la validation du téléphone mobile activée, une fois l'enregistrement des informations effectuées, le message demandant la saisie du code de confirmation est incorrect : 
_Merci de valider l'enregistrement en **saissant** le code SMS reçu_

à remplacer par : 
_Merci de valider l'enregistrement en **saisissant** le code SMS reçu_

La correction est à faire à la ligne 67 du fichier src/main/webapp/partials/membership.html.
j'aurai pu faire un pull ...

**Comment by prigaux** [comment]
Corrigé
