### ISSUE TITLE
Ecran Approbation : modifier le texte affiché lorsque la liste est vide

### ISSUE THREAD

**Issue by JGallot** [EsupPortail/esup-smsu#26]
Tout est dans le titre.

Avec notre cellule accompagnement, nous avons préféré remplacer le texte 
"Pas de message à approuver."

par  "Tous les messages ont été approuvés."

dans le fichier ./main/webapp/js/translations.js

Est-il possible de faire de même ?

**Comment by pixel** [comment]
Ok.
Un pull request ? ou je fais ?

**Comment by prigaux** [comment]
Ok.
Un pull request ? ou je fais ?
